# Flight Delay Dataset - Data Wrangling

This jupyter notebook describes the wrangling of the dataset required for the visualization using Tableau within Udacity's Data Analyst Project 08: "Create a Tableau Story".

As a dataset, we have chosen the Flight Delay Dataset, which can be found [here](https://www.transtats.bts.gov/OT_Delay/OT_DelayCause1.asp?pn=1) (note: the zip file is downloaded manually since a period of time has to be selected.). The source is the Bureau of Transportation Statistics (BTS), Airline Service Quality Performance 234

In further analysis and visualization, we want to take a look at the data of the recent 8 years to explore temporal trends. Thus, the period of the recent available data has been choosen, in our case from Aug, 2010 to Aug, 2018. Additional data from this site are also required to get more geographical data.

## Gathering

We gather Flights data from the [website](https://www.transtats.bts.gov/OT_Delay/OT_DelayCause1.asp?pn=1). Therefor, we download the data manually. The archive is then unzipped and converted into a Pandas dataframe programmatically, so we can assess the data in the next step of the data wrangling process.

In [19]:
# Import required modules to the python notebook
import pandas as pd
import numpy as np
import requests
import matplotlib.pyplot as plt
import zipfile
import datetime

%matplotlib inline

In [20]:
# Unzip the PISA archive
zipped_data = zipfile.ZipFile('airline_delay_causes.zip', 'r')
zipped_data.extractall()
zipped_data.close()

In [21]:
# Read CSV file
df_flight = pd.read_csv('airline_delay_causes.zip')
df_flight.head()

,year,month,carrier,carrier_name,airport,airport_name,arr_flights,arr_del15,carrier_ct,weather_ct,...,late_aircraft_ct,arr_cancelled,arr_diverted,arr_delay,carrier_delay,weather_delay,nas_delay,security_delay,late_aircraft_delay,Unnamed: 21
0,2010,8,9E,Pinnacle Airlines Inc.,ABE,"Allentown/Bethlehem/Easton, PA: Lehigh Valley ...",65.0,10.0,9.79,0.0,...,0.00,2.0,0.0,807.0,766.0,0.0,41.0,0.0,0.0,NaN
1,2010,8,9E,Pinnacle Airlines Inc.,ACK,"Nantucket, MA: Nantucket Memorial",14.0,2.0,1.00,0.0,...,0.96,0.0,0.0,178.0,70.0,0.0,4.0,0.0,104.0,NaN
2,2010,8,9E,Pinnacle Airlines Inc.,AEX,"Alexandria, LA: Alexandria International",2.0,0.0,0.00,0.0,...,0.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN
3,2010,8,9E,Pinnacle Airlines Inc.,ALB,"Albany, NY: Albany International",89.0,12.0,6.99,0.0,...,3.00,1.0,1.0,636.0,419.0,0.0,59.0,0.0,158.0,NaN
4,2010,8,9E,Pinnacle Airlines Inc.,AMA,"Amarillo, TX: Rick Husband Amarillo International",91.0,12.0,8.25,0.0,...,2.63,2.0,1.0,477.0,376.0,0.0,21.0,0.0,80.0,NaN

## Assessing

We look at the dataset in detail to identify structural or content-related issues that affect the data tidiness respectively the data quality.

In [22]:
# View summary of dataset using info()-function
df_flight.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 119144 entries, 0 to 119143
Data columns (total 22 columns):
year                   119144 non-null int64
 month                 119144 non-null int64
carrier                119144 non-null object
carrier_name           119144 non-null object
airport                119144 non-null object
airport_name           119144 non-null object
arr_flights            119013 non-null float64
arr_del15              118991 non-null float64
carrier_ct             119013 non-null float64
 weather_ct            119013 non-null float64
nas_ct                 119013 non-null float64
security_ct            119013 non-null float64
late_aircraft_ct       119013 non-null float64
arr_cancelled          119013 non-null float64
arr_diverted           119013 non-null float64
 arr_delay             119013 non-null float64
 carrier_delay         119013 non-null float64
weather_delay          119013 non-null float64
nas_delay              119013 non-null float64
security_delay         119013 non-null float64
late_aircraft_delay    119013 non-null float64
Unnamed: 21            0 non-null float64
dtypes: float64(16), int64(2), object(4)
memory usage: 18.2+ MB

In [23]:
# Check for NaN values in the "arr_del15" column (variable describes the amount of delayed flights)
df_flight[df_flight["arr_del15"].isnull()]

,year,month,carrier,carrier_name,airport,airport_name,arr_flights,arr_del15,carrier_ct,weather_ct,...,late_aircraft_ct,arr_cancelled,arr_diverted,arr_delay,carrier_delay,weather_delay,nas_delay,security_delay,late_aircraft_delay,Unnamed: 21
3506,2010,10,EV,Atlantic Southeast Airlines,FSM,"Fort Smith, AR: Fort Smith Regional",1.0,NaN,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN
3604,2010,10,F9,Frontier Airlines Inc.,OKC,"Oklahoma City, OK: Will Rogers World",NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3847,2010,10,OH,Comair Inc.,CAK,"Akron, OH: Akron-Canton Regional",NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4581,2010,11,9E,Pinnacle Airlines Inc.,TRI,"Bristol/Johnson City/Kingsport, TN: Tri Cities",NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5304,2010,11,OH,Comair Inc.,AVP,"Scranton/Wilkes-Barre, PA: Wilkes Barre Scrant...",NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5370,2010,11,OH,Comair Inc.,SAT,"San Antonio, TX: San Antonio International",NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6194,2010,12,B6,JetBlue Airways,AVP,"Scranton/Wilkes-Barre, PA: Wilkes Barre Scrant...",NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9927,2011,2,YV,Mesa Airlines Inc.,ATW,"Appleton, WI: Appleton International",1.0,NaN,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN
10164,2011,3,B6,JetBlue Airways,ORF,"Norfolk, VA: Norfolk International",NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11534,2011,4,CO,Continental Air Lines Inc.,SPN,"Saipan, TT: Francisco C. Ada Saipan International",NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12503,2011,4,XE,ExpressJet Airlines Inc.,SPI,"Springfield, IL: Abraham Lincoln Capital",NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12873,2011,5,DL,Delta Air Lines Inc.,HOU,"Houston, TX: William P Hobby",NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13025,2011,5,EV,Atlantic Southeast Airlines,MSP,"Minneapolis, MN: Minneapolis-St Paul Internati...",NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14633,2011,6,OO,SkyWest Airlines Inc.,BGM,"Binghamton, NY: Greater Binghamton/Edwin A. Li...",NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14865,2011,6,US,US Airways Inc.,IAD,"Washington, DC: Washington Dulles International",NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14999,2011,6,XE,ExpressJet Airlines Inc.,BFF,"Scottsbluff, NE: Western Neb. Regional/William...",1.0,NaN,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN
15618,2011,7,EV,Atlantic Southeast Airlines,LNK,"Lincoln, NE: Lincoln Airport",NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15650,2011,7,EV,Atlantic Southeast Airlines,RIC,"Richmond, VA: Richmond International",NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15943,2011,7,OO,SkyWest Airlines Inc.,AZO,"Kalamazoo, MI: Kalamazoo/Battle Creek Internat...",NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16329,2011,7,XE,ExpressJet Airlines Inc.,COS,"Colorado Springs, CO: City of Colorado Springs...",1.0,NaN,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN
16696,2011,8,CO,Continental Air Lines Inc.,ELP,"El Paso, TX: El Paso International",NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18667,2011,9,OO,SkyWest Airlines Inc.,ROW,"Roswell, NM: Roswell International Air Center",NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19342,2011,10,DL,Delta Air Lines Inc.,AGS,"Augusta, GA: Augusta Regional at Bush Field",NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20242,2011,10,XE,ExpressJet Airlines Inc.,EFD,"Houston, TX: Ellington",1.0,NaN,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN
20349,2011,10,YV,Mesa Airlines Inc.,HSV,"Huntsville, AL: Huntsville International-Carl ...",1.0,NaN,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN
24214,2012,1,YV,Mesa Airlines Inc.,SBN,"South Bend, IN: South Bend International",NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27509,2012,4,UA,United Air Lines Inc.,BQN,"Aguadilla, PR: Rafael Hernandez",NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28139,2012,5,EV,ExpressJet Airlines Inc.,BGR,"Bangor, ME: Bangor International",NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28669,2012,5,OO,SkyWest Airlines Inc.,SBN,"South Bend, IN: South Bend International",NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28699,2012,5,UA,United Air Lines Inc.,BQN,"Aguadilla, PR: Rafael Hernandez",NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
91628,2016,11,EV,ExpressJet Airlines Inc.,MIA,"Miami, FL: Miami International",NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
91994,2016,11,OO,SkyWest Airlines Inc.,ENV,"Wendover, UT: Wendover Airport",NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
93011,2016,12,OO,SkyWest Airlines Inc.,PNS,"Pensacola, FL: Pensacola International",1.0,NaN,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN
93129,2016,12,VX,Virgin America,ONT,"Ontario, CA: Ontario International",NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
93737,2017,1,EV,ExpressJet Airlines Inc.,TKI,"Tokeen, AK: Tokeen Airport",NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
96520,2017,4,DL,Delta Air Lines Inc.,BMI,"Bloomington/Normal, IL: Central Illinois Regional",NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
97565,2017,5,DL,Delta Air Lines Inc.,BIS,"Bismarck/Mandan, ND: Bismarck Municipal",NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
98273,2017,5,VX,Virgin America,SLC,"Salt Lake City, UT: Salt Lake City International",1.0,NaN,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN
98814,2017,6,EV,ExpressJet Airlines Inc.,GTR,"Columbus, MS: Golden Triangle Regional",NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
99535,2017,7,EV,ExpressJet Airlines Inc.,GUC,"Gunnison, CO: Gunnison-Crested Butte Regional",NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
101866,2017,9,DL,Delta Air Lines Inc.,JNU,"Juneau, AK: Juneau International",NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
101947,2017,9,EV,ExpressJet Airlines Inc.,AUS,"Austin, TX: Austin - Bergstrom International",1.0,NaN,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN
102040,2017,9,EV,ExpressJet Airlines Inc.,MSY,"New Orleans, LA: Louis Armstrong New Orleans I...",2.0,NaN,0.0,0.0,...,0.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN
102381,2017,9,OO,SkyWest Airlines Inc.,SIT,"Sitka, AK: Sitka Rocky Gutierrez",NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
102430,2017,9,UA,United Air Lines Inc.,EGE,"Eagle, CO: Eagle County Regional",1.0,NaN,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN
102992,2017,10,EV,ExpressJet Airlines Inc.,ALB,"Albany, NY: Albany International",NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
103249,2017,10,EV,ExpressJet Airlines Inc.,JFK,"New York, NY: John F. Kennedy International",1.0,NaN,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN
104424,2017,11,OO,SkyWest Airlines Inc.,PWM,"Portland, ME: Portland International Jetport",NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
105321,2017,12,EV,ExpressJet Airlines Inc.,ABI,"Abilene, TX: Abilene Regional",NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
107163,2018,1,EV,ExpressJet Airlines Inc.,MDT,"Harrisburg, PA: Harrisburg International",NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
107411,2018,1,MQ,Envoy Air,BDL,"Hartford, CT: Bradley International",NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
109067,2018,3,9E,Endeavor Air Inc.,CAK,"Akron, OH: Akron-Canton Regional",NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
109094,2018,3,9E,Endeavor Air Inc.,GRB,"Green Bay, WI: Green Bay Austin Straubel Inter...",NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
109107,2018,3,9E,Endeavor Air Inc.,LNK,"Lincoln, NE: Lincoln Airport",NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
111130,2018,4,DL,Delta Air Lines Inc.,MTJ,"Montrose/Delta, CO: Montrose Regional",NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
111283,2018,4,EV,ExpressJet Airlines Inc.,RSW,"Fort Myers, FL: Southwest Florida International",1.0,NaN,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN
113506,2018,5,OO,SkyWest Airlines Inc.,GSO,"Greensboro/High Point, NC: Piedmont Triad Inte...",NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
116416,2018,7,G4,Allegiant Air,BHM,"Birmingham, AL: Birmingham-Shuttlesworth Inter...",NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
117132,2018,7,UA,United Air Lines Inc.,SBA,"Santa Barbara, CA: Santa Barbara Municipal",1.0,NaN,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN
118586,2018,8,EV,ExpressJet Airlines Inc.,PIA,"Peoria, IL: General Downing - Peoria Internati...",1.0,NaN,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN

### Data Quality issues

- Missing values in some columns

- Date is not given as datetime object

- some column names are misleading

### Data Tidiness issues

- City, State and Airport are in the same column 

- "Unnamed:21" does not contain any data

- Year and Month in different columns

## Cleaning

Define, code and test the cleaning tasks, which have been identified in the assessment section.

### City, State and Airport are in the same column

#### Define
Split column airport_name and save each information in two different columns.

#### Code

In [24]:
# Split string in airport_name
airport_cols = df_flight["airport_name"].str.split(": ",expand=True)
# Create new columns in dataset
df_flight["airport_name"] = airport_cols[1]
df_flight["city"] = airport_cols[0]

#### Test

In [25]:
df_flight.sample(10)

,year,month,carrier,carrier_name,airport,airport_name,arr_flights,arr_del15,carrier_ct,weather_ct,...,arr_cancelled,arr_diverted,arr_delay,carrier_delay,weather_delay,nas_delay,security_delay,late_aircraft_delay,Unnamed: 21,city
31739,2012,8,EV,ExpressJet Airlines Inc.,PWM,Portland International Jetport,275.0,94.0,35.57,0.36,...,8.0,1.0,4654.0,2110.0,10.0,1025.0,0.0,1509.0,NaN,"Portland, ME"
95207,2017,2,WN,Southwest Airlines Co.,HOU,William P Hobby,3786.0,574.0,111.12,16.92,...,36.0,6.0,22377.0,4472.0,2065.0,6418.0,0.0,9422.0,NaN,"Houston, TX"
1030,2010,8,OO,SkyWest Airlines Inc.,OAK,Metropolitan Oakland International,149.0,11.0,3.66,1.00,...,0.0,0.0,771.0,185.0,18.0,55.0,0.0,513.0,NaN,"Oakland, CA"
37883,2013,1,EV,ExpressJet Airlines Inc.,CMH,John Glenn Columbus International,225.0,60.0,17.61,1.00,...,2.0,0.0,3131.0,716.0,131.0,984.0,0.0,1300.0,NaN,"Columbus, OH"
41584,2013,4,AA,American Airlines Inc.,ICT,Wichita Dwight D Eisenhower National,116.0,27.0,7.10,0.48,...,2.0,0.0,1477.0,502.0,29.0,138.0,0.0,808.0,NaN,"Wichita, KS"
58013,2014,4,VX,Virgin America,SFO,San Francisco International,1426.0,237.0,34.15,15.38,...,2.0,1.0,18667.0,2116.0,517.0,11268.0,11.0,4755.0,NaN,"San Francisco, CA"
97683,2017,5,DL,Delta Air Lines Inc.,SLC,Salt Lake City International,3771.0,417.0,154.20,4.96,...,0.0,12.0,25793.0,12116.0,200.0,3539.0,0.0,9938.0,NaN,"Salt Lake City, UT"
63224,2014,9,EV,ExpressJet Airlines Inc.,BOS,Logan International,176.0,23.0,11.91,0.00,...,2.0,0.0,1181.0,738.0,0.0,201.0,0.0,242.0,NaN,"Boston, MA"
32642,2012,9,AA,American Airlines Inc.,ORF,Norfolk International,55.0,34.0,15.13,1.11,...,1.0,0.0,3037.0,1506.0,36.0,222.0,0.0,1273.0,NaN,"Norfolk, VA"
47653,2013,8,OO,SkyWest Airlines Inc.,DEN,Denver International,4331.0,786.0,111.51,19.49,...,48.0,18.0,48569.0,10063.0,1258.0,11374.0,23.0,25851.0,NaN,"Denver, CO"

### "Unnamed:21" does not contain any data

#### Define
The column "Unnamed: 21" has to be dropped.

#### Code

In [26]:
# Drop column "Unnamed: 21"
df_flight.drop(["Unnamed: 21"], axis=1, inplace=True)

#### Test

In [27]:
# View dataset summary
df_flight.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 119144 entries, 0 to 119143
Data columns (total 22 columns):
year                   119144 non-null int64
 month                 119144 non-null int64
carrier                119144 non-null object
carrier_name           119144 non-null object
airport                119144 non-null object
airport_name           119144 non-null object
arr_flights            119013 non-null float64
arr_del15              118991 non-null float64
carrier_ct             119013 non-null float64
 weather_ct            119013 non-null float64
nas_ct                 119013 non-null float64
security_ct            119013 non-null float64
late_aircraft_ct       119013 non-null float64
arr_cancelled          119013 non-null float64
arr_diverted           119013 non-null float64
 arr_delay             119013 non-null float64
 carrier_delay         119013 non-null float64
weather_delay          119013 non-null float64
nas_delay              119013 non-null float64
security_delay         119013 non-null float64
late_aircraft_delay    119013 non-null float64
city                   119144 non-null object
dtypes: float64(15), int64(2), object(5)
memory usage: 17.7+ MB

### Year and Month in different columns

#### Define
Year and Month belong to one variable (date) but are separated in two columns, which is in indicator for 'messy data'.
Both variables have to be concatenated as a string in one column. Since no week or day information are given in the dataset, we assume the first of each month to create a complete date.
Columns Year and Month can be dropped.

#### Code

In [28]:
# put Year and Month together in one column as a string
df_flight["date"] = df_flight["year"].map(str) + "-" + df_flight[" month"].map("{:02}".format) + "-01"

# Drop Year and Month
df_flight.drop(["year"," month"], axis=1, inplace=True)

#### Test

In [29]:
# View Sample of rows
df_flight.sample(10)

,carrier,carrier_name,airport,airport_name,arr_flights,arr_del15,carrier_ct,weather_ct,nas_ct,security_ct,...,arr_cancelled,arr_diverted,arr_delay,carrier_delay,weather_delay,nas_delay,security_delay,late_aircraft_delay,city,date
47394,F9,Frontier Airlines Inc.,ATL,Hartsfield-Jackson Atlanta International,47.0,18.0,4.78,0.26,8.02,0.00,...,0.0,0.0,595.0,120.0,5.0,283.0,0.0,187.0,"Atlanta, GA",2013-08-01
112364,YX,Republic Airline,TLH,Tallahassee International,56.0,6.0,0.83,0.00,2.49,0.00,...,1.0,0.0,237.0,60.0,0.0,55.0,0.0,122.0,"Tallahassee, FL",2018-04-01
91255,AA,American Airlines Inc.,EGE,Eagle County Regional,13.0,1.0,0.00,0.00,1.00,0.00,...,0.0,0.0,39.0,0.0,0.0,39.0,0.0,0.0,"Eagle, CO",2016-11-01
29586,FL,AirTran Airways Corporation,DSM,Des Moines International,59.0,4.0,0.00,0.00,0.00,0.00,...,2.0,1.0,366.0,0.0,0.0,0.0,0.0,366.0,"Des Moines, IA",2012-06-01
65589,EV,ExpressJet Airlines Inc.,BHM,Birmingham-Shuttlesworth International,276.0,66.0,21.00,0.00,26.08,0.00,...,0.0,1.0,3195.0,919.0,0.0,1098.0,0.0,1178.0,"Birmingham, AL",2014-11-01
96538,DL,Delta Air Lines Inc.,COS,City of Colorado Springs Municipal,30.0,9.0,1.92,2.72,1.74,0.75,...,3.0,0.0,461.0,40.0,255.0,45.0,62.0,59.0,"Colorado Springs, CO",2017-04-01
74917,EV,ExpressJet Airlines Inc.,GJT,Grand Junction Regional,31.0,1.0,0.00,0.00,1.00,0.00,...,0.0,0.0,31.0,0.0,0.0,31.0,0.0,0.0,"Grand Junction, CO",2015-07-01
63376,F9,Frontier Airlines Inc.,ANC,Ted Stevens Anchorage International,20.0,6.0,1.25,0.00,4.75,0.00,...,0.0,0.0,132.0,24.0,0.0,108.0,0.0,0.0,"Anchorage, AK",2014-09-01
23678,MQ,American Eagle Airlines Inc.,LBB,Lubbock Preston Smith International,172.0,23.0,9.93,2.95,4.87,0.00,...,7.0,1.0,915.0,423.0,134.0,154.0,0.0,204.0,"Lubbock, TX",2012-01-01
97160,UA,United Air Lines Inc.,IAH,George Bush Intercontinental/Houston,4475.0,497.0,143.48,9.62,165.75,0.00,...,3.0,19.0,32794.0,10548.0,1009.0,7350.0,0.0,13887.0,"Houston, TX",2017-04-01

### Date is not given as datetime object

#### Define
The created date column is given as string and has to be converted into datetime object.

#### Code

In [30]:
# Format date to datetime object
df_flight["date"] = pd.to_datetime(df_flight["date"], format='%Y-%m-%d')

#### Test

In [31]:
# Check info()-function for datatype of column date
df_flight.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 119144 entries, 0 to 119143
Data columns (total 21 columns):
carrier                119144 non-null object
carrier_name           119144 non-null object
airport                119144 non-null object
airport_name           119144 non-null object
arr_flights            119013 non-null float64
arr_del15              118991 non-null float64
carrier_ct             119013 non-null float64
 weather_ct            119013 non-null float64
nas_ct                 119013 non-null float64
security_ct            119013 non-null float64
late_aircraft_ct       119013 non-null float64
arr_cancelled          119013 non-null float64
arr_diverted           119013 non-null float64
 arr_delay             119013 non-null float64
 carrier_delay         119013 non-null float64
weather_delay          119013 non-null float64
nas_delay              119013 non-null float64
security_delay         119013 non-null float64
late_aircraft_delay    119013 non-null float64
city                   119144 non-null object
date                   119144 non-null datetime64[ns]
dtypes: datetime64[ns](1), float64(15), object(5)
memory usage: 16.8+ MB

### Missing values in some columns

#### Define
Some delay information are missing in the dataset. Corresponding rows are useless for the analysis and visualization of flight delays or cancellations. Thus, these observations can be dropped.

#### Code

In [32]:
# Drop rows with NaN in the "arr_flight" column
df_flight.dropna(inplace=True)

#### Test

In [33]:
# Check the info()-function - all columns have to be exactly the same amount of non-null values
df_flight.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 118991 entries, 0 to 119143
Data columns (total 21 columns):
carrier                118991 non-null object
carrier_name           118991 non-null object
airport                118991 non-null object
airport_name           118991 non-null object
arr_flights            118991 non-null float64
arr_del15              118991 non-null float64
carrier_ct             118991 non-null float64
 weather_ct            118991 non-null float64
nas_ct                 118991 non-null float64
security_ct            118991 non-null float64
late_aircraft_ct       118991 non-null float64
arr_cancelled          118991 non-null float64
arr_diverted           118991 non-null float64
 arr_delay             118991 non-null float64
 carrier_delay         118991 non-null float64
weather_delay          118991 non-null float64
nas_delay              118991 non-null float64
security_delay         118991 non-null float64
late_aircraft_delay    118991 non-null float64
city                   118991 non-null object
date                   118991 non-null datetime64[ns]
dtypes: datetime64[ns](1), float64(15), object(5)
memory usage: 17.7+ MB

### Some column names are misleading

#### Define
Rename column names using a dictionary.

#### Code

In [34]:
# Define a dictionary and rename columns
new_cols = {"carrier":"Carrier",
            "carrier_name": "Carrier_Name",
            "airport":"Airport",
            "airport_name":"Airport_Name",
            "arr_flights":"Flights_count",
            "arr_del15":"Delays_count",
            "carrier_ct":"Carrier_Delays_count",
            " weather_ct":"Weather_Delays_count",
            "nas_ct":"NAS_Delays_count",
            "security_ct":"Security_Delays_count",
            "late_aircraft_ct":"Late_Aircraft_Delays_count",
            "arr_cancelled":"Cancellations_count",
            "arr_diverted":"Diversions_count",
            " arr_delay":"Delay_minutes",
            " carrier_delay":"Carrier_Delay_minutes",
            "weather_delay":"Weather_Delay_minutes",
            "nas_delay":"NAS_Delay_minutes",
            "security_delay":"Security_Delay_minutes",
            "late_aircraft_delay":"Late_Aircraft_Delay_minutes",
            "city":"City",
            "date":"Date"}
df_flight.rename(index=str, columns=new_cols,inplace=True)

#### Test

In [35]:
df_flight.info()

<class 'pandas.core.frame.DataFrame'>
Index: 118991 entries, 0 to 119143
Data columns (total 21 columns):
Carrier                        118991 non-null object
Carrier_Name                   118991 non-null object
Airport                        118991 non-null object
Airport_Name                   118991 non-null object
Flights_count                  118991 non-null float64
Delays_count                   118991 non-null float64
Carrier_Delays_count           118991 non-null float64
Weather_Delays_count           118991 non-null float64
NAS_Delays_count               118991 non-null float64
Security_Delays_count          118991 non-null float64
Late_Aircraft_Delays_count     118991 non-null float64
Cancellations_count            118991 non-null float64
Diversions_count               118991 non-null float64
Delay_minutes                  118991 non-null float64
Carrier_Delay_minutes          118991 non-null float64
Weather_Delay_minutes          118991 non-null float64
NAS_Delay_minutes              118991 non-null float64
Security_Delay_minutes         118991 non-null float64
Late_Aircraft_Delay_minutes    118991 non-null float64
City                           118991 non-null object
Date                           118991 non-null datetime64[ns]
dtypes: datetime64[ns](1), float64(15), object(5)
memory usage: 17.2+ MB

## Storage

We store the dataset as a new Excel-file.

In [36]:
# Save to Excel-file
df_flight.to_excel('flight_delays.xlsx',index=False)